---
# This playbook deploys the whole web application stack in this server.

- name: HOSTING SETUP
  hosts: host
  remote_user: root
  roles:
    - { role: preparing, when: ansible_distribution == "CentOS" }
    - { role: user, when: ansible_distribution == "CentOS" }
    - { role: common, when: ansible_distribution == "CentOS" }
    - { role: files, when: ansible_distribution == "CentOS" }
    - { role: php, when: ansible_distribution == "CentOS" }
    - { role: cli, when: ansible_distribution == "CentOS" }
    - { role: httpd, when: ansible_distribution == "CentOS" }
    - { role: mysql, when: ansible_distribution == "CentOS" }
    - { role: selinux, when: ansible_distribution == "CentOS" }
    - { role: firewalld, when: ansible_distribution == "CentOS" }
    - { role: backup, when: ansible_distribution == "CentOS" }
    - { role: cron, when: ansible_distribution == "CentOS" }
    - { role: install, when: ansible_distribution == "CentOS" }
    - { role: reboot, when: ansible_distribution == "CentOS" }
