---
# This playbook will install MariaDB

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - MariaDB
    - MariaDB-server
    - MySQL-python
  tags: mariadb

- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mariadb

- name: Create MariaDB log file
  file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0775

- name: Create MariaDB PID directory
  file:
    path: /var/run/mysqld
    state: directory
    owner: mysql
    group: mysql
    mode: 0775

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes
